steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/insurance-hub-397016/aiunited:${SHORT_SHA}",
        "-t",
        "gcr.io/insurance-hub-397016/aiunited:latest",
        "--cache-from",
        "gcr.io/insurance-hub-397016/aiunited:latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/insurance-hub-397016/aiunited:${SHORT_SHA}"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "aiunited",
        "--region=us-east1",
        "--platform=managed",
        "--image=gcr.io/insurance-hub-397016/aiunited:${SHORT_SHA}",
      ]
images:
  [
    "gcr.io/insurance-hub-397016/aiunited:${SHORT_SHA}",
    "gcr.io/insurance-hub-397016/aiunited:latest",
  ]
