steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker pull  gcr.io/insurance-hub-397016/aiunited:latest || exit 0",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/insurance-hub-397016/aiunited:latest",
        "--cache-from",
        "gcr.io/insurance-hub-397016/aiunited:latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/insurance-hub-397016/aiunited:latest"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "aiunited",
        "--region=us-east1",
        "--platform=managed",
        "--image=gcr.io/insurance-hub-397016/aiunited:latest",
      ]
images: ["gcr.io/insurance-hub-397016/aiunited:latest"]
